// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/proto/compute/v1/test_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JunkyardService_MakeMyDayBetter_FullMethodName = "/compute.v1.junkyardService/MakeMyDayBetter"
)

// JunkyardServiceClient is the client API for JunkyardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JunkyardServiceClient interface {
	// MakeMyDayBetter responds with a "friendly" message depending on the contents of the Request
	MakeMyDayBetter(ctx context.Context, in *MakeMyDayBetterRequest, opts ...grpc.CallOption) (*MakeMyDayBetterResponse, error)
}

type junkyardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJunkyardServiceClient(cc grpc.ClientConnInterface) JunkyardServiceClient {
	return &junkyardServiceClient{cc}
}

func (c *junkyardServiceClient) MakeMyDayBetter(ctx context.Context, in *MakeMyDayBetterRequest, opts ...grpc.CallOption) (*MakeMyDayBetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeMyDayBetterResponse)
	err := c.cc.Invoke(ctx, JunkyardService_MakeMyDayBetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JunkyardServiceServer is the server API for JunkyardService service.
// All implementations must embed UnimplementedJunkyardServiceServer
// for forward compatibility.
type JunkyardServiceServer interface {
	// MakeMyDayBetter responds with a "friendly" message depending on the contents of the Request
	MakeMyDayBetter(context.Context, *MakeMyDayBetterRequest) (*MakeMyDayBetterResponse, error)
	mustEmbedUnimplementedJunkyardServiceServer()
}

// UnimplementedJunkyardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJunkyardServiceServer struct{}

func (UnimplementedJunkyardServiceServer) MakeMyDayBetter(context.Context, *MakeMyDayBetterRequest) (*MakeMyDayBetterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeMyDayBetter not implemented")
}
func (UnimplementedJunkyardServiceServer) mustEmbedUnimplementedJunkyardServiceServer() {}
func (UnimplementedJunkyardServiceServer) testEmbeddedByValue()                         {}

// UnsafeJunkyardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JunkyardServiceServer will
// result in compilation errors.
type UnsafeJunkyardServiceServer interface {
	mustEmbedUnimplementedJunkyardServiceServer()
}

func RegisterJunkyardServiceServer(s grpc.ServiceRegistrar, srv JunkyardServiceServer) {
	// If the following call pancis, it indicates UnimplementedJunkyardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JunkyardService_ServiceDesc, srv)
}

func _JunkyardService_MakeMyDayBetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeMyDayBetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JunkyardServiceServer).MakeMyDayBetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JunkyardService_MakeMyDayBetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JunkyardServiceServer).MakeMyDayBetter(ctx, req.(*MakeMyDayBetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JunkyardService_ServiceDesc is the grpc.ServiceDesc for JunkyardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JunkyardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compute.v1.junkyardService",
	HandlerType: (*JunkyardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeMyDayBetter",
			Handler:    _JunkyardService_MakeMyDayBetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/compute/v1/test_service.proto",
}
